---

- name: "Create a directory to be mounted"
  file:
    path: "{{ mount_storage_path }}"
    state: directory
    mode: 0755

- name: "Unmount existing shared storage"
  become: yes
  mount:
    path: "{{ mount_storage_path }}"
    state: unmounted

- name: "Mount the shared storage"
  shell: nohup sshfs {{ host_storage_src }} {{ mount_storage_path }} &
